import type { NpcProfile, NpcState } from "@ai-town/shared";

export const DEMO_WORLD_ID = "world_qixi_town";
export const DEMO_USER_ID = "user_demo";

export const demoWorld = {
  id: DEMO_WORLD_ID,
  name: "栖溪镇",
  description: "周末河岸市集正在筹备的现代滨河社区。",
};

type SeedNpc = { profile: NpcProfile; state: NpcState };

export const demoNpcs: SeedNpc[] = [
  {
    profile: {
      id: "npc_lin_xia",
      name: "林夏",
      age: 31,
      role: "栖岸咖啡馆主理人 / 市集协办人",
      color: "#e9704f",
      personality: "外向热心、责任感强，压力大时容易过度控制局面。",
      motivation: "弥补上次活动取消的失误，并让市集收入缓解咖啡馆经营压力。",
      preferences: ["清晰的计划", "清晨", "兑现承诺"],
      dislikes: ["临时失约", "准备不足", "混乱"],
      traits: { sociability: 88, conscientiousness: 92, curiosity: 58, riskTolerance: 36 },
    },
    state: {
      npcId: "npc_lin_xia",
      locationId: "cafe",
      position: { x: 265, y: 190 },
      currentAction: "整理市集清单",
      actionReason: "开店前先确认今天的准备事项。",
      actionEndsAtMinute: 500,
      hunger: 28,
      energy: 76,
      mood: 68,
      stress: 48,
      social: 34,
    },
  },
  {
    profile: {
      id: "npc_shen_zhiheng",
      name: "沈知衡",
      age: 36,
      role: "安宁诊所医生",
      color: "#4f8fca",
      personality: "理性谨慎、情绪克制，表面疏离但会在真正需要时主动承担。",
      motivation: "让社区居民获得可靠的照护，并确保市集急救点足够安全。",
      preferences: ["证据", "晨跑", "安静的茶"],
      dislikes: ["未经证实的消息", "冒险行事", "夸大病情"],
      traits: { sociability: 42, conscientiousness: 95, curiosity: 63, riskTolerance: 22 },
    },
    state: {
      npcId: "npc_shen_zhiheng",
      locationId: "clinic",
      position: { x: 725, y: 190 },
      currentAction: "检查急救箱",
      actionReason: "市集前需要确认急救物资。",
      actionEndsAtMinute: 500,
      hunger: 32,
      energy: 82,
      mood: 61,
      stress: 24,
      social: 29,
    },
  },
  {
    profile: {
      id: "npc_he_jianguo",
      name: "何建国",
      age: 55,
      role: "老何杂货铺老板",
      color: "#b47a3c",
      personality: "务实节俭、看重互惠与可兑现的承诺，嘴上谨慎却会照顾熟客。",
      motivation: "守住库存和现金流，同时不让老街坊在关键时刻缺东西。",
      preferences: ["准时", "象棋", "账目清楚"],
      dislikes: ["浪费", "长期赊欠", "空口保证"],
      traits: { sociability: 57, conscientiousness: 86, curiosity: 28, riskTolerance: 18 },
    },
    state: {
      npcId: "npc_he_jianguo",
      locationId: "grocery",
      position: { x: 265, y: 432 },
      currentAction: "清点饮料库存",
      actionReason: "市集会增加需求，先弄清库存再答应供货。",
      actionEndsAtMinute: 500,
      hunger: 22,
      energy: 71,
      mood: 55,
      stress: 36,
      social: 40,
    },
  },
  {
    profile: {
      id: "npc_zhou_fang",
      name: "周放",
      age: 27,
      role: "社区配送员",
      color: "#568f5c",
      personality: "灵活乐观、行动优先，珍视自由和义气，经济压力下偶尔冒险接单。",
      motivation: "多完成几单改善收入，也不想辜负一直照顾自己的街坊。",
      preferences: ["音乐", "捷径", "爽快的人"],
      dislikes: ["繁琐手续", "被同情", "长时间等待"],
      traits: { sociability: 74, conscientiousness: 61, curiosity: 84, riskTolerance: 79 },
    },
    state: {
      npcId: "npc_zhou_fang",
      locationId: "riverside",
      position: { x: 460, y: 370 },
      currentAction: "查看配送路线",
      actionReason: "早高峰前先找一条更快的路线。",
      actionEndsAtMinute: 500,
      hunger: 44,
      energy: 79,
      mood: 73,
      stress: 31,
      social: 46,
    },
  },
  {
    profile: {
      id: "npc_tang_yucheng",
      name: "唐雨澄",
      age: 26,
      role: "栖溪社区报记者",
      color: "#8c65ae",
      personality: "观察敏锐、有公共责任感，也渴望做出有影响力的报道。",
      motivation: "完成一篇真实而有价值的市集报道，不把不确定消息放大成事实。",
      preferences: ["核验信息", "河岸摄影", "具体回答"],
      dislikes: ["敷衍", "封锁消息", "无来源的传言"],
      traits: { sociability: 68, conscientiousness: 78, curiosity: 96, riskTolerance: 51 },
    },
    state: {
      npcId: "npc_tang_yucheng",
      locationId: "community",
      position: { x: 725, y: 410 },
      currentAction: "整理采访提纲",
      actionReason: "先准备问题，避免报道只剩热闹。",
      actionEndsAtMinute: 500,
      hunger: 35,
      energy: 74,
      mood: 66,
      stress: 27,
      social: 38,
    },
  },
];

